Buf stats
flucoma/flucoma-docs pull request #103
Opened 2022-04-28 11:32 UTC by tedmoore

2022-04-28 12:18 UTC, tremblap requested changes
good work. I'm missing the graph we had though, but I reckon you will make a clear link to the learn page when it is ready? Where/how will that be?

(same with the info removed on IQR I reckon)

typo: it's corresponding channel -> its

2022-04-28 13:49 UTC, tedmoore commented
> I'm missing the graph we had though, but I reckon you will 

What graph?

> make a clear link to the learn page when it is ready? Where/how will that be?

Yes, I think for this object because it is quite big, a link to the Learn will be appropriate. @jamesb93 said he's planning to automatically add a link to every RST. Is this still true?

2022-04-28 13:51 UTC, tremblap commented
> What graph?

the table/graph that was there in the original help showing the data structure

> Is this still true?

even if it is, in certain case where it is abstract like this, we'd like to point at it directly I think

2022-04-28 16:48 UTC, tedmoore commented
@tremblap, I put the table back in!

2022-04-29 04:31 UTC, jamesb93 commented
> > I'm missing the graph we had though, but I reckon you will
> 
> What graph?
> 
> > make a clear link to the learn page when it is ready? Where/how will that be?
> 
> Yes, I think for this object because it is quite big, a link to the Learn will be appropriate. @jamesb93 said he's planning to automatically add a link to every RST. Is this still true?

Yeah it's on my list of things to think about it. I'm torn over two ways of doing it which are in the template or just manually...

2022-04-29 04:33 UTC, jamesb93 approved these changes

2022-04-29 04:33 UTC, jamesb93 commented on doc/BufStats.rst
> +:digest: Statistically summarise a time series in a Buffer
I like

2022-05-10 21:10 UTC, merged