(Buf)AmpGate RST & SC examples
flucoma/flucoma-docs pull request #122
Opened 2022-05-27 14:55 UTC by tedmoore

2022-05-31 09:13 UTC, jamesb93 requested changes
I think this missing a didactic example about lookback/ahead which the Max documentation seems to have. I think it's valuable and already exists in Max, though I'm not sure about SC and maybe you removed it or it was never there in the first place.


![image](https://user-images.githubusercontent.com/13281862/171138439-9ba6c3d6-ee7d-4cc2-90aa-ecee5f84819b.png)

2022-05-31 09:13 UTC, jamesb93 commented on doc/AmpGate.rst
> +:description: Absolute amplitude threshold gate detector on a real-time signal
I think "realtime" as opposed to "real-time" is the more consistent way to put it with the rest of the documentation.

2022-05-31 09:13 UTC, jamesb93 commented on doc/AmpGate.rst
> +:description: Absolute amplitude threshold gate detector on a real-time signal
It also makes it more consistent when the inevitable "non-realtime" appears

2022-05-31 09:23 UTC, tremblap commented
> I think this missing a didactic example about lookback/ahead which the Max documentation seems to have. 

it definitely was in there originally but everything was plotting :)

2022-05-31 12:32 UTC, tremblap requested changes
I also miss (like @jamesb93 ) the visual example that were provided as tutorial to understand it all.

2022-05-31 12:32 UTC, tremblap commented on doc/AmpGate.rst
> +:description: Absolute amplitude threshold gate detector on a real-time signal
agreed

2022-05-31 13:13 UTC, tremblap commented
obviously the buf version with waveform to look at is much clearer!

2022-05-31 14:39 UTC, tedmoore commented
> the visual example that were provided as tutorial to understand it all.

I'm not sure what you're referring to. I just looked back at the help files. If you're referring to something that is in here (see picture below). I deleted all this--it was testing the parameters one by one and felt way cold and uninviting. If there's a particular visual display that you want added back in, I can make that happen.

<img width="960" alt="Screenshot 2022-05-31 at 15 39 29" src="https://user-images.githubusercontent.com/1531144/171200635-c617552f-a868-4d6f-bf25-30258e27adde.png">

2022-05-31 18:24 UTC, tremblap commented
> I'm not sure what you're referring to.

that code. in max it is less ugly because of scope and rt but it helps - see the picture @jamesb93 showed above.

2022-06-01 09:25 UTC, tedmoore commented
I would prefer to not have code in the help file that looks like this--it's not clear what a user is supposed to take a way from it or how to use it. I think the Max version is more clear and approachable. Can you specify for me in a few sentences what is most important to elucidate or demonstrate for the user and I can try to do that succinctly?

2022-06-01 09:30 UTC, tremblap commented
I think the Max version's narrative (changing setting, described expected behaviour, look at the gate) is quite good. I translated it from the SC example initially, so I think it is doing that, but if you think of a better, more interactive way to look at gates with commented dynamic preset changes, then I'm happy. The idea is that one can observe the wave and the gate, and hear the state change. it is very multimodal teaching in max...

2022-06-01 09:59 UTC, jamesb93 commented
> I think the Max version's narrative (changing setting, described expected behaviour, look at the gate) is quite good. I translated it from the SC example initially, so I think it is doing that, but if you think of a better, more interactive way to look at gates with commented dynamic preset changes, then I'm happy. The idea is that one can observe the wave and the gate, and hear the state change. it is very multimodal teaching in max...

Let's remember that this is up for debate before Max get's changed also. I don't love the narrative style – it has the potential to be confusing when it is as long and didactic as this. I actually don't currently think the Max one offers that much either, sorry. Some vertical markers move around a synthetic waveform. As @tedmoore said it is difficult for a user to take much away from this without already knowing what they need to know. I prefer something that is like an actual narrative based on a problematic use case, like the Constanzo drum sample and capturing different levels of intricacy.

2022-06-01 10:43 UTC, jamesb93 commented
> Ok, well, I'm glad @jamesb93 said so because I agree with him. I think tweaking the parameters needs some motivation and some highlighting like, "see, now the slice point is specified before the drum hit onset, even though it's triggered after the onset" and being zoomed into to see the few hundred samples difference. I could poke at a narrative of trying to see these parameters move around a drum hit perhaps?

I think that is a good path forward – contextualise this nitty gritty in real use case so it sticks.

2022-06-14 09:30 UTC, merged