(Buf)Transients(Slice) Family
flucoma/flucoma-docs pull request #140
Opened 2022-06-08 14:34 UTC by tedmoore

2022-06-08 14:48 UTC, jamesb93 requested changes
Some particular comments from me but I think the examples are good. Looking forward to porting them to the Max realm.

2022-06-08 14:48 UTC, jamesb93 commented on doc/TransientSlice.rst
> +  TransientSlice identifies slice points in a real time signal by implementing a "de-clicking" algorithm based on the assumption that a transient is a sample or series of samples that are anomalous w
anomalous when compared to surrounding samples

2022-06-08 14:48 UTC, jamesb93 commented on doc/TransientSlice.rst
> +  TransientSlice identifies slice points in a real time signal by implementing a "de-clicking" algorithm based on the assumption that a transient is a sample or series of samples that are anomalous w
Not sure samples' should be possessive about the time series. I would say It creates an autoregressive model of the samples as a time series.

2022-06-08 14:48 UTC, jamesb93 commented on doc/TransientSlice.rst
> +  The process will return an audio steam with sample-long impulses at estimated starting points of the different slices.
sample-long > single sample

2022-06-08 14:48 UTC, jamesb93 commented on doc/TransientSlice.rst
> +  How many previous samples are used by the algorithm to create the autoregressive model of the signal within the ``blockSize`` window of analysis.. The higher the ``order``, the more accurate is its
How > The number of

2022-06-08 14:59 UTC, weefuzzy requested changes

2022-06-08 14:59 UTC, weefuzzy commented on doc/BufTransientSlice.rst
> +  BufTransientSlice identifies slice points in a buffer by implementing a "de-clicking" algorithm based on the assumption that a transient is a sample or series of samples that are anomalous when com
it's "error" -> its "error"

2022-06-08 14:59 UTC, weefuzzy commented on doc/BufTransientSlice.rst
> +  The series of samples determined to be a transient will continue until the error goes below ``threshBack``, indicating that the samples are again more in-line with the autoregressive model.
To be clear, there are *two* error signals here, forward and backward, so this isn't just a schmitt trigger on a single curve.

2022-06-08 14:59 UTC, weefuzzy commented on doc/BufTransientSlice.rst
> +  How many previous samples are used by the algorithm to create the autoregressive model of the signal within the ``blockSize`` window of analysis.. The higher the ``order``, the more accurate is its
Not sure that the spectral resolution stuff is illuminating here, but yes, higher order models will cope better with more distal temporal dependencies in data, which translates to handling low frequencies better

2022-06-08 14:59 UTC, weefuzzy commented on doc/BufTransientSlice.rst
> + The threshold applied to the smoothed error function for determining an onset. The units are roughly in standard deviations, thus can be considered how "deviant", or anomalous, the signal must be to
smoothed forward error function

2022-06-08 14:59 UTC, weefuzzy commented on doc/BufTransientSlice.rst
> + The threshold applied to the smoothed error function for determining an onset. The units are roughly in standard deviations, thus can be considered how "deviant", or anomalous, the signal must be to
or even forward prediction error

2022-06-08 14:59 UTC, weefuzzy commented on doc/BufTransientSlice.rst
> + The threshold applied to the smoothed error function for determining an offset. The units are roughly in standard deviations, thus can be considered how "deviant", or anomalous, the signal must be t
ditto backward

2022-06-08 14:59 UTC, weefuzzy commented on doc/BufTransientSlice.rst
>  :control action:
do we need documentation for `action`s. I still can't remember 😄

2022-06-08 15:51 UTC, tedmoore commented on doc/BufTransientSlice.rst
> +  The series of samples determined to be a transient will continue until the error goes below ``threshBack``, indicating that the samples are again more in-line with the autoregressive model.
@weefuzzy Yeah, I gathered that that is the case. Is it ok to allow our reader to think of it as Schmitt Trigger that uses these critera as onset and offset detectors? (This explanation can yet change, just trying to not overexplain things)

2022-06-09 14:34 UTC, tremblap requested changes
a great explanation, a few proposals, and a few bugs.

2022-06-09 14:34 UTC, tremblap commented on doc/BufTransientSlice.rst
> +  BufTransientSlice identifies slice points in a buffer by implementing a "de-clicking" algorithm based on the assumption that a transient is a sample or series of samples that are anomalous when com
maybe taming down 'autoregressive' by saying just before - it creates a model to predict something similar to its surrounding via autoregression (in proper english - but defering the algo after the explanation of guestimating continuation)

2022-06-09 14:34 UTC, tremblap commented on doc/BufTransientSlice.rst
> + The nervousness of the bespoke detection function. It ranges from -10 to 10 (it has no units) representing the strength and direction of some nonlinearity applied to the detection signal which contr
high is ambiguous in high values. positive values?

2022-06-09 14:34 UTC, tremblap commented on doc/BufTransients.rst
> +  This implements a "de-clicking" algorithm based on the assumption that a transient is a sample or series of samples that are anomalous when compared to surrounding samples. It creates an autoregres
same remark as above in the RT version

2022-06-09 14:34 UTC, tremblap commented on doc/TransientSlice.rst
> +  TransientSlice identifies slice points in a real time signal by implementing a "de-clicking" algorithm based on the assumption that a transient is a sample or series of samples that are anomalous w
and here again

2022-06-09 14:34 UTC, tremblap commented on doc/Transients.rst
> +   This implements a "de-clicking" algorithm based on the assumption that a transient is a sample or series of samples that are anomalous when compared to surrounding samples. It creates an autoregre
and here. I wonder if there isn't a way to not copy that text 4 times.

2022-06-09 14:34 UTC, tremblap commented on example-code/sc/Transients.scd
> +	FluidTransients.ar(PlayBuf.ar(1, b, loop:1));
bug: reading b and not ~src

2022-06-09 14:34 UTC, tremblap commented on example-code/sc/Transients.scd
> +	var sig = PlayBuf.ar(1, b, loop:1);
same bug not playing ~src

2022-06-09 14:34 UTC, tremblap commented on example-code/sc/BufTransients.scd
> +FluidWaveform(~compare,bounds:Rect(0,0,1600,1200));
maybe zooming in to see the difference?

2022-06-10 11:06 UTC, tedmoore commented on example-code/sc/BufTransients.scd
> +FluidWaveform(~compare,bounds:Rect(0,0,1600,1200));
FluidWaveform doesn't have zoom yet.

2022-06-10 11:15 UTC, merged

2022-06-10 11:24 UTC, tremblap commented on example-code/sc/BufTransients.scd
> +FluidWaveform(~compare,bounds:Rect(0,0,1600,1200));
I know but one could use 1 second of source sound instead and we can see the wave...