[Enhance] Add CCE specific see also sections to transformer and template
flucoma/flucoma-docs pull request #73
Opened 2022-02-08 21:56 UTC by jamesb93

- add default transformer cases for cce_seealso
- add data so that it renders in the templates
- added {pd/max}_seealso example for Pitch.yaml

2022-02-08 23:18 UTC, weefuzzy requested changes

2022-02-08 23:18 UTC, weefuzzy commented on flucoma/doc/templates/pd_htmlref.html
> +    <h3 class="seealso_name"><a href="{{ s }}.html">{{ s }}</a></h3>
maybe strip the `<a>` – presumably it's not linking anywhere useful if it's for generic PD objects

2022-02-08 23:18 UTC, weefuzzy commented on flucoma/doc/transformers.py
> +    try:
This seems like overkill. Does it need a warning. Wouldn't 
```python 
data['max_seealso`] = data.get('max_seealso`,'').split(',') 
```

do the trick, without the need for try..except?

2022-02-08 23:18 UTC, weefuzzy commented on flucoma/doc/transformers.py
> +    try:
give or take some curious use of backticks instead of single quotes

2022-02-08 23:35 UTC, jamesb93 commented on flucoma/doc/transformers.py
> +    try:
Have to say I prefer my overkill as its obvious what happens in either scenario. Happy to budge if you think its better to go your way though

2022-02-08 23:36 UTC, jamesb93 commented on flucoma/doc/templates/pd_htmlref.html
> +    <h3 class="seealso_name"><a href="{{ s }}.html">{{ s }}</a></h3>
Ah is the HTML doc a FluCoMa specific thing? In the case, indeed bye bye html

2022-02-08 23:38 UTC, jamesb93 commented on flucoma/doc/transformers.py
> +    try:
Just going from my own experience parsing the transformer code for the first time I found the many nested dict.pop() sort of stuff quite windy to get my head around but thats just my 2c.

2022-02-09 00:29 UTC, jamesb93 commented on flucoma/doc/templates/pd_htmlref.html
> +    <h3 class="seealso_name"><a href="{{ s }}.html">{{ s }}</a></h3>
Done

2022-02-09 00:30 UTC, jamesb93 commented on flucoma/doc/transformers.py
> +    try:
Okay this is much more simplified now :)

2022-02-09 00:30 UTC, weefuzzy approved these changes

2022-02-09 15:22 UTC, tedmoore approved these changes
This is great. My only reservation is that now we have
* `see-also` which is FluCoMa related
* `max-seealso`
* `pd-seealso`
* `sc-related` -- which is actually in SC called "see also", so maybe we need to change `sc-related` to `sc-seealso` 

and I wouldnt be opposed to changing `see-also` to `flucoma-seealso`.

I think this would make more clear to anyone coming into the RST what these are for and which are parallel to each other.

2022-02-09 15:24 UTC, jamesb93 commented
The naming being consistent would make it obvious how all those bits talk to each other, I agree. What does @weefuzzy think of that?

2022-02-10 12:21 UTC, jamesb93 commented
Ths is also made slightly more complicated by the YAMl to RST conversion so I think it best to put it into a separate PR

2022-02-10 12:24 UTC, merged